### ISSUE TITLE
The pipeline used"Create PanGenie-ready VCF from Minigraph-Cactus VCF"

### ISSUE THREAD

**Issue by ld9866** [eblerjana/genotyping-pipelines#1]
Dear developer:
We were building a graph pan-genome using MC, we used "Create PanGenie-ready VCF from Minigraph-Cactus VCF" workflow, but we found that it was not feasible as soon as possible without any errors, resulting in missing files without being generated. I would like to ask how this tube can be transplanted and used in MC results of other mammals?
Thank you!

**Comment by ld9866** [comment]
The code: snakemake -j 10
Building DAG of jobs...
Creating conda environment env/merging.yml...
Downloading and installing remote packages.
Environment for env/merging.yml created (location: .snakemake/conda/197f0388)
Using shell: /usr/bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	add_ids
	1	all
	1	merge_haplotypes
	1	normalize
	1	prepare_vcf
	5

[Tue Dec 19 15:18:16 2023]
rule prepare_vcf:
    input: /home/test/Data/PanGenie/pangenie-ready.vcf
    output: /home/test/Data/PanGenie/results/input-vcf/input-missing-removed.vcf
    log: /home/test/Data/PanGenie/results/input-vcf/prepare-vcf.log
    jobid: 4
    benchmark: /home/test/Data/PanGenie/results/benchmarks/prepare-vcf.txt
    wildcards: outdir=/home/test/Data/PanGenie/results

Activating conda environment: /data/test/PanGenie/vcf-merging/pangenome-graph-from-callset/.snakemake/conda/197f0388
[Tue Dec 19 15:18:17 2023]
Error in rule prepare_vcf:
    jobid: 4
    output: /home/test/Data/PanGenie/results/input-vcf/input-missing-removed.vcf
    log: /home/test/Data/PanGenie/results/input-vcf/prepare-vcf.log (check log file(s) for error message)
    conda-env: /data/test/PanGenie/vcf-merging/pangenome-graph-from-callset/.snakemake/conda/197f0388
    shell:
        cat /home/test/Data/PanGenie/pangenie-ready.vcf | python3 scripts/prepare-vcf.py --missing 0.2 2> /home/test/Data/PanGenie/results/input-vcf/prepare-vcf.log 1> /home/test/Data/PanGenie/results/input-vcf/input-missing-removed.vcf
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job prepare_vcf since they might be corrupted:
/home/test/Data/PanGenie/results/input-vcf/input-missing-removed.vcf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by ld9866** [comment]
If we used the prepare-vcf.py separately, the code showed that:
Traceback (most recent call last):
  File "/data/test/PanGenie/vcf-merging/pangenome-graph-from-callset/scripts/prepare-vcf.py", line 43, in <module>
    raise Exception('VCF contains unphased positions.')
Exception: VCF contains unphased positions.

**Comment by eblerjana** [comment]
Hi,

the error message indicates that your input VCF is not phased. The pipeline is designed for VCFs produced by the Minigraph-Cactus pipeline. Note that, as mentioned in the README, this pipeline is designed for human data only.

**Comment by ld9866** [comment]
Thank  you!
